id: P004603
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG8833
  title: མངོན་པ་མཛོད་ཀྱི་དགོངས་དོན་གསལ་བྱེད་ལེགས་བཤད་ཉིན་བྱེད་དབང་པོའི་སྣང་བ་དང་།
    མཛོད་སྡོམ་བཅས།
  author: ''
  volumes:
    4acabf13e2ea4acab915411e811f7ef4:
      image_group_id: I1KG8875
      title: ''
      volume_number: 1
      total_pages: 726
